name: HRMS Pipeline

on:
  push:
    branches:
      - main-dev

jobs:
  pipeline-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up JDK
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11'
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package
      
    - name: Build Docker image
      run: docker build -t hrms-springboot .
